# Generated by Django 4.1.7 on 2023-03-02 09:05

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=58)),
                ('product_caption', models.TextField(max_length=128)),
                ('product_thumbnail', models.ImageField(upload_to='products/thumbnails/')),
                ('product_slug', models.SlugField(max_length=58, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product_views', models.IntegerField(default=0)),
                ('product_description', models.TextField(max_length=1024)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_sale_percentage', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('product_sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('product_meta_name', models.CharField(max_length=58)),
                ('product_meta_caption', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_slug', models.SlugField(unique=True)),
                ('category_image', models.ImageField(upload_to='category_images/')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='products.productcategory')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('category_slug', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
