# Generated by Django 4.1.7 on 2023-02-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.IntegerField(default=0),
        ),
    ]
