# Generated by Django 4.1.7 on 2023-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(upload_to='products/thumbnails/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.FileField(upload_to='products/gallery/images/%Y/%m/'),
        ),
    ]
