# Generated by Django 4.1.7 on 2023-02-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
