# Generated by Django 4.1.7 on 2023-03-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Products',
            new_name='products',
        ),
    ]
